# Generated by Django 5.2.6 on 2025-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('ogden', 'Ogden'), ('slc', 'Salt Lake City'), ('logan', 'Logan'), ('park city', 'Park City'), ('st. george', 'St. George')])),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
