# Generated by Django 5.2.6 on 2025-12-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Ogden', 'ogden'), ('Salt Lake City', 'slc'), ('Logan', 'logan'), ('Park City', 'park city'), ('St. George', 'st. george')]),
        ),
    ]
